name: Auto Release on Version Change

on:
  push:
    branches:
      - master
      - v2

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version from composer.json
        id: get_version
        run: echo "version=$(jq -r '.version' composer.json)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check if tag exists
        id: check_tag
        run: |
          EXISTS=$(git ls-remote --tags origin refs/tags/${{ steps.get_version.outputs.version }} | wc -l)
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT
        shell: bash

      - name: Determine if prerelease
        id: is_prerelease
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" =~ (alpha|beta|rc|wip) ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Create Release if tag doesn't exist
        if: steps.check_tag.outputs.exists == '0'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: ${{ steps.is_prerelease.outputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
